version: '3'
services:
  postgresql:
    image: postgres:10
    container_name: postgresql
    hostname: postgresql-server
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./database:/docker-entrypoint-initdb.d
    environment:
      - TZ=Asia/Tokyo
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_INITDB_ARGS:--encoding=UTF-8 --locale=C
    restart: always
volumes:
  db-data:
    driver: local
